{{ config(materialized="table", schema="silver_airbnb") }}

select
    id,
    host_id,
    host_name,
    host_since,
    host_location,
    host_neighbourhood,
    host_listings_count,
    host_total_listings_count,
    host_identity_verified,
    neighbourhood,
    neighbourhood_cleansed,
    property_type,
    room_type,
    accommodates,
    bedrooms,
    beds,
    amenities,
    cast(replace(replace(price, '$', ''), ',', '') as float) as price,
    minimum_nights,
    maximum_nights,
    minimum_minimum_nights,
    maximum_minimum_nights,
    minimum_maximum_nights,
    maximum_maximum_nights,
    minimum_nights_avg_ntm,
    maximum_nights_avg_ntm,
    availability_30,
    availability_60,
    availability_90,
    availability_365,
    number_of_reviews,
    number_of_reviews_ltm,
    number_of_reviews_l30d,
    review_scores_rating,
    review_scores_accuracy,
    review_scores_cleanliness,
    review_scores_checkin,
    review_scores_communication,
    review_scores_location,
    review_scores_value
from {{ ref("bronze_detailed_listings") }}
